version: '1'
services:
  backend:
    build:
      context: ../backend
      dockerfile: ./Dockerfile
    image: resource365-backend:1.0.19
    restart: always
    ports:
      - 3333:3333
  frontend:
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
    image: resource365-frontend:1.0.19
    depends_on:
      - backend
    ports:
      # Host:Container
      - 4200:80
    volumes:
    - ../frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro